
muleApp:
  environment: "dev"
  apiAutoDiscoveryId: "16395549"
  
json:
  logger.application.name : "uca-tameenk-api"
  logger.application.version : "1.0"
  maskFields: "password"
  

db:
  host: "10.2.11.122"
  user: "Rasool"
  password: "Asim@123"
  dbname: "mule"      

vpms:
  url: "http://10.2.11.103:8080/vpms.product/calculation/UCA_SA_CarInsurance_Retail/transient"
  param: "choice,hasChoice,hidden_commit,id,editable,required,relevant,caption,description,addCaption,removeCaption,canAddGroup,canRemoveGroup"    
  